version: '3'

networks:
  app-tier:
    driver: bridge

services:
  wihire-app:
    build: .
    networks:
      - app-tier
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    env_file:
      - .env
    

  postgres: 
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - 8001:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    networks:
      - app-tier