version: '3'

networks:
  app-tier:
    driver: bridge

services:
  wihire-app:
    build: .
    networks:
      - app-tier
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/wihire?schema=public"
    
  postgres: 
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - '8001:5432'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "wihire"
      POSTGRES_PORT: "5432"
    networks:
      - app-tier
