exports.PERMISSION_ERR_MSG = 'You not allowed to access this resource'
exports.AUTH_ERR_MSG = 'You are not authenticated'
exports.AUTHORIZATION_ERR_MSG = 'You are not authorized'
exports.FORBIDDEN_ERR_MSG = "You don't have access"
exports.CLIENT_ERR_MSG = 'Client error'
exports.INVARIANT_ERR_MSG = 'Invariant error'
exports.NOT_FOUND_ERR_MSG = 'Not found error'
exports.TOKEN_INVALID_ERR_MSG = 'Token invalid'
exports.TOKEN_EXPIRED_ERR_MSG = 'Token expired'
