name: Deployment

on: [ push, pull_request ]

jobs:
  # --- check lint ---------------
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing depedencies
        run: yarn install
      - name: Running test lint
        run: yarn lint:check
